### ISSUE TITLE
爆炸粒子颜色

### ISSUE THREAD

**Issue by WengHaobin** [ViceFantasyPlace/activate-power-mode#11]
我看README里面爆炸粒子是有不同颜色 可是为什么我装了以后只有黑色和白色（黑色主题显白色，白色主题显黑色）？求作者解答！感谢

**Comment by zhimajiang** [comment]
彩色特效默认没有开的，需要的话，勾选windows->activate-power-mode->colorful

**Comment by WengHaobin** [comment]
OK  解决了 感谢

**Comment by trampboy** [comment]
你好，非常感谢你的分享，效果很不错，不过我开启了colorful，用的是0.0.8版本，仍然看不到爆炸粒子，白色和黑色Theme下都是，不知道是什么原因。
