### ISSUE TITLE
phpstrom找不到创建Plugin的Configuration

### ISSUE THREAD

**Issue by webfans** [ViceFantasyPlace/activate-power-mode#24]
已经成功安装了jar包，但是进入Run/Debug Configurations根本找不到，**plugin** 这个选项，到底怎么添加配置项

一定要注意：第一次运行如果没有运行配置需要创建一个Plugin Configuration 
Edit Run/Debug Configurations -> add a new Plugin Configuration 【phpstrom2016.3 找不到】
-> 在 Use classpath of module 选择 activate-power-mode 【找不到】
-> Apply

**Comment by KADO-C** [comment]
安装 Plugin jar包
Preferences/Plugins 
-> Install plugin from disk 
-> 选择 jar文件 
-> Apply 
-> 重启编辑器 
安装jar包后重启就可以的了

**Comment by webfans** [comment]
KADO-C说得对，是这样的！起初我这样安装的JAR包的，但半天就是无法触发特效！后来不知就突然就好了，现在正在使用中，很炫！
