### ISSUE TITLE
能不能适配android studio呀

### ISSUE THREAD

**Issue by sujianqingfeng** [ViceFantasyPlace/activate-power-mode#25]
如题

**Comment by KADO-C** [comment]
@sujianqingfeng android studio 能用啊  我日常也是在android studio上用的

**Comment by sujianqingfeng** [comment]
可以用了 谢啦 第二天开电脑就能用了

**Comment by SSSSHIELD** [comment]
Android Studio上的Run/Edit Configurations里面没得Plugins这个选项，无法将jar配置到当前项目中去，所以即使安装了jar包之后，，也用不了。。
