### ISSUE TITLE
建议把窗口抖动和火花效果都做个快捷键开关

### ISSUE THREAD

**Issue by ushang000** [ViceFantasyPlace/activate-power-mode#3]
建议把窗口抖动和火花效果都做个快捷键开关，最好有个设置界面

**Comment by zhimajiang** [comment]
加了，在window menu -> activate-power-mode那里可以进行开关，迟点再做个设置界面，可以设置火花速度，个数，震动幅度之类的

**Comment by ushang000** [comment]
我是把这个jar包导入到android studio 里了，但是没看到有window menu -> activate-power-mode这个选项啊，或者快捷键是什么？还是jar包有更新

**Comment by ushang000** [comment]
嗯，可以设置选择火花颜色，或者样式什么的，仅供参考。
