### ISSUE TITLE
已经半年没更新了....

### ISSUE THREAD

**Issue by BetterPHPer** [ViceFantasyPlace/activate-power-mode#34]
不想要8秒内敲击30 Combo以上才有效果.
抓紧搞个设置界面,可以自由设置是不是直接出现效果,或者敲击多少下才出现效果

**Comment by xionghhcs** [comment]
源码应该可以改，可以把源码git下来，再自己修改再打包，然后再装

**Comment by zhimajiang** [comment]
已经更新加入了combo开关了，现在安装最新版

**Comment by zhimajiang** [comment]
最新版已经更新加入了combo开关了

**Comment by BetterPHPer** [comment]
我刚发完这个issue作者就已经更新啦!
