### ISSUE TITLE
add a new Plugin Configuration 后 在 Use classpath of module 没有可选项

### ISSUE THREAD

**Issue by WPNEAL** [ViceFantasyPlace/activate-power-mode#35]
![tim 20170721111517](https://user-images.githubusercontent.com/16266197/28447828-f3d1e570-6e05-11e7-98f7-264e5780a422.png)
![tim 20170721111524](https://user-images.githubusercontent.com/16266197/28447834-f92780d4-6e05-11e7-8ba0-65c860f2e6e7.png)

**Comment by zhimajiang** [comment]
你是要开发么，不开发可以不弄这个…

**Comment by WPNEAL** [comment]
主要是安装上没反应,然后看readme里面写的'第一次运行如果没有运行配置需要创建一个Plugin的Configuration'....

**Comment by WPNEAL** [comment]
刚让朋友试了下,可以,我重装试试

**Comment by WPNEAL** [comment]
重装后,过会有效果了,谢谢dalao的插件
