### ISSUE TITLE
Mac下不起作用

### ISSUE THREAD

**Issue by fooololo** [ViceFantasyPlace/activate-power-mode#36]
1. 按教程下载jar，plugin中install from disk
2. IDEA版本：2017.2.1
3. 系统：MacOS Sierra

**Comment by zhimajiang** [comment]
直接插件搜索activate-power-mode就可以安装了

**Comment by fooololo** [comment]
直接搜索安装也是一样的，无效果

**Comment by zhimajiang** [comment]
是不是开了combo开关，如果开了combo开关需要连打才能出现效果

**Comment by fooololo** [comment]
确实是开了combo，感谢！
