### ISSUE TITLE
考不考虑来个亮瞎模式？

### ISSUE THREAD

**Issue by hentai-mew** [ViceFantasyPlace/activate-power-mode#4]
开启亮瞎模式后，把小雪花搞成随机的五颜六色的小方块 hhhhh
正常模式就是白色的.... 
娱乐想法... 勿喷 持续关注项目发展 有时间尝试贡献代码自己修改一个

**Comment by hentai-mew** [comment]
额 包含亮瞎模式的功能我已经自己实现啦.... 

这是效果图：
![image](http://7xl780.com1.z0.glb.clouddn.com/zhuangbi%2F1.gif)

顺便项目结构不是很好，没有使用构建工具 也没有依赖说明 我是直接新建了gradle管理的project 然后进行二次开发的。。。

**Comment by KADO-C** [comment]
可以的呀～大家交流一下代码嘛
