### ISSUE TITLE
combo数和max combo可视化怎么关，关闭的按钮在哪里，不想显示出来

### ISSUE THREAD

**Issue by jameingh** [ViceFantasyPlace/activate-power-mode#58]
# combo数和max combo可视化怎么关
关闭的按钮在哪里，不想显示出来

**Comment by yeminv** [comment]
![image](https://user-images.githubusercontent.com/25047579/34705111-eb425cd6-f538-11e7-988e-157a51a88336.png)
combo点掉就可以了，idea重启下

**Comment by KADO-C** [comment]
v0.1.7就像@yeminv那样操作，v0.1.8就不需要重启

**Comment by jameingh** [comment]
ok
