### ISSUE TITLE
0.0.7.jar 没有火花效果只有窗口抖动效果

### ISSUE THREAD

**Issue by ushang000** [ViceFantasyPlace/activate-power-mode#8]
activate-power-mode 0.0.7.jar 没有火花效果只有窗口抖动效果

**Comment by KADO-C** [comment]
是么  我刚才试过有的，你看下windos -> activate-power-mode -> particle 有没有勾上， 或者关闭文件文件分页重新打开一个文件试试

**Comment by ushang000** [comment]
ok了，我重新安装就好了，是必须打开新文件吗？我重新装的就没有打开新文件

**Comment by KADO-C** [comment]
正常来说是不用的，不过如果更新了插件要重启一下idea才会生效，因为代码里面是如果重新打开一个文件就会重新把新分页的JComponent给ParticlePanel，所以就想叫你重新打开一个文件试试
